version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./app:/var/www/html/app

  mysql:
    image: mysql
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 13306:3306
